#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#hello:
#    path: /
#    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#    defaults:
#      template: 'hello.html.twig'
